version: '3'

services:

  backendserver:
    image: covid-cases-back
    ports:
           - "8080:8080"

    restart: always
  frontend:
    image: covid-cases-front
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "4200:80"      